language: node_js
node_js:
  - "node"
before_script:
  # Install Webpack version
  - npm install @vue/cli -g
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"
stages:
  - lint
  - build
install:
  - npm install
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master